### ISSUE TITLE
What Should go in pressure_control_set field?? 

### ISSUE THREAD

**Issue by vaishvikr** [clif-consortium/CLIF#1]
Can someone clarify what will go in this field, An example will be helpful.
![image](https://github.com/user-attachments/assets/4e147599-4469-4c2e-99e7-3b3113a2d85f)

**Comment by clif-consortium** [comment]
@vaishvikr we mapped a flowsheet element called "PC Set" / "RT RS VENT PRESSURES PC SET" to pressure_control_set
