### ISSUE TITLE
Medicatins missing 

### ISSUE THREAD

**Issue by sajor2000** [clif-consortium/CLIF#18]
https://github.com/clif-consortium/CLIF/blob/main/mCIDE/clif_medication_admin_continuous_med_categories.csv   

  Reviewing our current medication list, we've identified that sodium chloride (NaCl) is included (line 65: sodium chlorideothers). However, we've noticed that several other common resuscitation fluids are not present. These include:

1. Lactated Ringer's solution
2. Albumin infusion 
3. Plasma-Lyte
4. Dextrose in water (D5W) ?

**Comment by clif-consortium** [comment]
@kaveriC update the medication category list

**Comment by clif-consortium** [comment]
Added the above four meds to the med categories list under fluid_electrolytes med_group
