### ISSUE TITLE
Move hospital_id  to the hospitalization table from the ADT table

### ISSUE THREAD

**Issue by clif-consortium** [clif-consortium/CLIF#20]
move `hospital_id`  to the hospitalization table if we make a new hopsitalization_id when a patient gets transferred within a health system

**Comment by 08wparker** [comment]
@clif-consortium 

1. add `patient_id` to ADT
2. If a patient is transferred between different hospitals within a health system, a new `hospitalization_id` should be created
3. ER data prior an inpatient admission should be included in the same `hospitalization_id`
4. @ingra107 will work on a Post-CLIF script that constructs a `healthsystem_stay_id` for patients who are transferred between hospitals within a healthsystem
