### ISSUE TITLE
need to add a `transfusion` table

### ISSUE THREAD

**Issue by 08wparker** [clif-consortium/CLIF#41]
| **Variable Name**        | **Data Type** | **Definition**                                                                                  | **Permissible Values**          |
|---------------------------|---------------|--------------------------------------------------------------------------------------------------|---------------------------------|
| `hospitalization_id`      | VARCHAR       | Unique identifier linking the transfusion event to a specific hospitalization in the CLIF database. | Unique identifier, e.g., `123456` |
| `transfusion_start_dttm`  | DATETIME      | The date and time the transfusion of the blood component began.                                   | Example: `2024-12-03 08:30:00` |
| `transfusion_end_dttm`    | DATETIME      | The date and time the transfusion of the blood component ended.                                   | Example: `2024-12-03 10:00:00` |
| `component_name`          | VARCHAR       | The name of the blood component transfused.                                                      | E.g., `Red Blood Cells`, `Plasma`, `Platelets` |
| `attribute_name`          | VARCHAR       | Attributes describing modifications to the component.                                             | E.g., `Leukocyte Reduced`, `Irradiated` |
| `volume_transfused`       | DOUBLE        | The volume of the blood component transfused.                                                    | Example: `300`                 |
| `volume_units`            | VARCHAR       | The unit of measurement for the transfused volume.                                               | Example: `mL`                  |
| `product_code`            | VARCHAR       | ISBT 128 Product Description Code representing the specific blood product.                       | Example: `E0382`               |

**Comment by 08wparker** [comment]
@clif-consortium can you add this to the data dictionary with a concept maturity?

**Comment by clif-consortium** [comment]
@08wparker Added to the data dictionary and status tracker.
