### ISSUE TITLE
ETL Meds at UCMC issue with including anesthetics into Vasoactives

### ISSUE THREAD

**Issue by ingra107** [clif-consortium/CLIF#7]
![image](https://github.com/user-attachments/assets/1939b04b-02c4-4214-af8f-161766aacae0)

See example of UCMC meds.  We need to be careful about not including meds in the wrong grouper when they are combo!  
Just wanted to give the UofC team a heads up on that!

**Comment by 08wparker** [comment]
thanks @ingra107 , @kaveriC  this should not be mapped to `epinephrine`

**Comment by ingra107** [comment]
I figured out a way to mitigate some of these issues by doing a rowwise() function so that it only chooses one and then moves on... you then put epi AFTER bupivicane so the "other" category gets found first before Epi comes up.  you need to do this with sodium chloride and bicarb too.  Those essentially need to be last because tons of things are mixed with that.  If you just do matching you will get many to many.  The only issue is that we still want Lidocaine as a cardiac med... so that will have to be manually fixed on the pre-clif side of things.  I am sure there are other things like that along the way.  Here is the code I use. Keep in mind that I have a tibble with the med_cateogry and med_grouper just like whats on the google sheet except I reordered them as described above.  Then I use the code below.  It takes every distinct med_name and finds a med_cat and group.  Then i can just join it back

`medication_names <-  df_med_cohort_1 |> select(med_name) |> distinct()

# Create a column to store matched categories in medication_names
medication_names <- medication_names %>%
  rowwise() %>%  # Operate row-wise to apply the logic to each med_name individually
  mutate(matched_category = list(
    medication_grouper$med_category_grouper[str_detect(med_name, regex(medication_grouper$med_category_grouper, ignore_case = TRUE))]
  )) %>%
  ungroup()  # Ungroup after operation

# Unlist the matched categories to make it more readable
medication_names <- medication_names %>%
  mutate(matched_category = sapply(matched_category, function(x) ifelse(length(x) > 0, x, NA)))

# Join the matched categories with the med_group from medication_grouper
medication_names <- medication_names %>% 
  left_join(medication_grouper, by = c("matched_category" = "med_category_grouper")) 
`
