### ISSUE TITLE
ADT: should there be an OR category or not

### ISSUE THREAD

**Issue by ingra107** [clif-consortium/CLIF#8]
Do we want OR to be mapped to `other` or do we want there to be an `OR` category?  I wonder if we just make a `Procedural/OR` or just `Procedural` category and ask people to put ANY peri/intra/post-procedure or peri/intra/post-operative categories into this category and remove all confusion.  Just a thought.  

![image](https://github.com/user-attachments/assets/9fbbdfd5-97c3-4aaa-88df-9f7e7008df71)

**Comment by ingra107** [comment]
Also... @kaveriC ... lets say we all agree to go with the plan above.  Is there a way that I can make the changes so it doesn't fall on you to do it?  Im assuming that means i create a branch or something and do a push or something, but if possible I would love to test it out and unburden you from small things like this!!

**Comment by 08wparker** [comment]
@ingra107 agree with a combination `procedural` `location_category` for all OR or procedure. That means there will not be many `other` locations in a typical CLIF database. Please fix this and then resolve this issue when the documentation has been updated. In general let's make that the workflow, keeping @kaveriC in the loop but the PI who "owns" the table can make changes like this.

**Comment by ingra107** [comment]
this has been updated and pushed without issues! see [ADT pull request](https://github.com/clif-consortium/website/pull/3)
